### ISSUE TITLE
Restart required on Ubuntu 18.04

### ISSUE THREAD

**Issue by Flowkap** [geerlingguy/ansible-role-nfs#35]
I'm afraid I don't know much more but until I perform a restart of the target system (plain Ubuntu server) i get errors on mounting (rejected by server) The share is exposed though. 

Any idea?

**Comment by Flowkap** [comment]
:/ Bump?

**Comment by elreydetoda** [comment]
@Flowkap, can you post the results of this: `journalctl -u "nfs-*.service" | tee nfs-service.log`

not a part of the project, but saw you issue when browsing the repo.
