### ISSUE TITLE
client only installation misbehaves

### ISSUE THREAD

**Issue by kostyrev** [geerlingguy/ansible-role-nfs#7]
I only want to mount nfs shares from remote servers but this role changes /etc/exports and notifies nfs server => so it's get started.
But I don't want nfs be started 'cause all I need is to mount remote shares.

**Comment by geerlingguy** [comment]
This could be added by adding a `when: nfs_exports|length` to the task that copies the configuration file. Doing that would mean that those who have exports, then remove them (so exports is empty) would not have the now-unwanted exports removed from the file (and thus the exports would remain active).

So this is a little tricky. maybe I could add a variable like `nfs_disable_server` that you could use to make sure NFS is never started or restarted.
