### ISSUE TITLE
Error when trying to enable nfs: rc=1 Failed to issue method call: No such file or directory

### ISSUE THREAD

**Issue by Hubbitus** [geerlingguy/ansible-role-nfs#9]
CentOS 7.

Service named nfs-server.

Task:
```
    - name: Ensure nfs is running.
      service: "name=nfs-server state=started enabled=yes"
```
works

**Comment by rajasaur** [comment]
+1 to the patch. Hit the same problem and got it resolved when the service name was changed to nfs-server

**Comment by geerlingguy** [comment]
Unfortunately RHEL/CentOS 6 still uses `nfs`, so we should make this dynamic and set it appropriately depending on the major version of RHEL.
